import turtle

turtle.pensize(6)

turtle.left(90)
turtle.forward(140)
turtle.right(90)
turtle.penup()
turtle.forward(70)
turtle.pendown()
turtle.forward(105)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(105)
turtle.left(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(105)
turtle.penup()
turtle.forward(70)
turtle.pendown()
turtle.forward(105)
turtle.left(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(60)
turtle.left(180)
turtle.forward(60)
turtle.left(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(105)

turtle.hideturtle()

turtle.exitonclick()

